//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.DY.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RoleInfo> RoleInfo { get; set; }
        public DbSet<TopicInfo> TopicInfo { get; set; }
        public DbSet<NewInfo> NewInfo { get; set; }
        public DbSet<PaityMember> PaityMember { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserActionInfo> UserAction { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<StudyOnline> StudyOnline { get; set; }
        public DbSet<Template> Template { get; set; }
        public DbSet<StudyItem> StudyItem { get; set; }
        public DbSet<FilesInfo> FilesInfo { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<ContentInfo> ContentInfo { get; set; }
        public DbSet<Friend> Friend { get; set; }
        public DbSet<VisitorRecord> VisitorRecord { get; set; }
    }
}
