//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.DY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaityMember
    {
        public PaityMember()
        {
            this.DelFlag = true;
            this.Status = 1;
            this.FilesInfo = new HashSet<FilesInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public string ClassNO { get; set; }
        public Nullable<System.DateTime> JoinYLTime { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> RegularTime { get; set; }
        public string ClassPosition { get; set; }
        public string Telphone { get; set; }
        public string IDCard { get; set; }
        public string RewardPunishment { get; set; }
        public string FailedSubject { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedTime { get; set; }
        public Nullable<int> UserInfoID { get; set; }
    
        public virtual ICollection<FilesInfo> FilesInfo { get; set; }
    }
}
