//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.DY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicInfo
    {
        public TopicInfo()
        {
            this.Status = 1;
            this.DelFlag = true;
            this.TopicInfoID = 0;
            this.UserInfo1 = new HashSet<UserInfo>();
            this.TopicInfo1 = new HashSet<TopicInfo>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedTime { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<int> TopicInfoID { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserInfo> UserInfo1 { get; set; }
        public virtual ICollection<TopicInfo> TopicInfo1 { get; set; }
        public virtual TopicInfo TopicInfo2 { get; set; }
    }
}
