//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNCJ.DY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Userpwd = "123456";
            this.Status = 1;
            this.DelFlag = true;
            this.RoleInfo = new HashSet<RoleInfo>();
            this.UserActionInfo = new HashSet<UserActionInfo>();
            this.TopicInfo = new HashSet<TopicInfo>();
            this.TopicInfo1 = new HashSet<TopicInfo>();
            this.StudyItem = new HashSet<StudyItem>();
            this.ContentInfo = new HashSet<ContentInfo>();
            this.Friend = new HashSet<Friend>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserKey { get; set; }
        public string Userpwd { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> ModfiedTime { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
        public virtual ICollection<UserActionInfo> UserActionInfo { get; set; }
        public virtual ICollection<TopicInfo> TopicInfo { get; set; }
        public virtual ICollection<TopicInfo> TopicInfo1 { get; set; }
        public virtual ICollection<StudyItem> StudyItem { get; set; }
        public virtual ICollection<ContentInfo> ContentInfo { get; set; }
        public virtual ICollection<Friend> Friend { get; set; }
    }
}
